project_id = "ixfgtcxthdjjftsltlrk"

[functions.generate-news]
verify_jwt = false

[functions.generate-news-stream]
verify_jwt = false

[functions.revise-text]
verify_jwt = false

[functions.search-news]
verify_jwt = false

[functions.auto-collect-news]
verify_jwt = false
